### ISSUE TITLE
Consolidate bug trackers?

### ISSUE THREAD

**Issue by Grinnz** [stevan/p5-MOP#19]
This dist (and related dists) seems to prefer the github issue tracker. If you add the following to the [MetaResources] plugin then metacpan/search.cpan will link to the github issue tracker, and the RT issue tracker will display a banner linking here as well, which could lessen potential confusion.

    bugtracker.web = https://github.com/stevan/p5-MOP/issues

**Comment by stevan** [comment]
Thanks added in 4e69de52730bd34e1a3a4720e072732509fd5941
