### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by grtodd** [stevan/p5-MOP#20]
**Installation instructions:**

`git clone https://github.com/stevan/p5-MOP; cd p5-MOP ; dzil build ; cd MOP-*/ ;  cpanm  .`

**Comment by grtodd** [comment]
One could of course add more, and more meaningful, text to said  file.

**Comment by stevan** [comment]
Those are not installation instructions actually, it should just be `cpanm MOP`, as this has been released to CPAN. 

But yeah, I need to add more to the README eventually.
