### ISSUE TITLE
Dependency on Devel::Hook not declared

### ISSUE THREAD

**Issue by andk** [stevan/p5-MOP#24]
As per subject. Grep:

http://search.cpan.org/grep?release=MOP-0.10;string=Devel::Hook;n=1;C=0

Sample fail report:

http://www.cpantesters.org/cpan/report/88270136

Matrix: http://matrix.cpantesters.org/?dist=MOP%200.10

**Comment by stevan** [comment]
Fixed in 0.11 on CPAN
